# Generated by Django 5.1 on 2024-09-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
