# Generated by Django 5.1 on 2024-09-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_department_is_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
