# Generated by Django 5.1 on 2024-09-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_taskcomment_employee_remove_taskcomment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(related_name='projects', to='api.employee'),
        ),
    ]
